name: CI for Spring Boot App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21 with Liberica distribution
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: graalvm

      # Step 3: Restore Maven cache using skjolber/maven-cache-github-action
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v3.1.1
        with:
          step: restore

      # Step 4: Build the Spring Boot application using Maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      # Step 5: Save Maven cache
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v3.1.1
        with:
          step: save
