@host = localhost
@port = 8080

# name login
POST https://examples.http-client.intellij.net/body-echo
Content-Type: application/json

{
  "token": "my-secret-token"
}

> {% client.global.set("auth_token", response.body.token); %}

###

# name login
//Accessing a variable
GET https://examples.http-client.intellij.net/headers
Authorization: Bearer {{auth_token}}

